Hw03 mongodb
RitaDyvnych/nodejs-homework-REST-api pull request #2
Opened 2021-12-26 13:33 UTC by RitaDyvnych

2021-12-26 15:06 UTC, KirillKulakow commented on controllers/contacts/index.js
> +  return res.status(HttpCode.OK).json({ status: 'success', code: HttpCode.OK, data: { ...contacts } })
объясни зачем данная строка `data: { ...contacts }`? в чем ее смысл?

2021-12-26 15:11 UTC, KirillKulakow requested changes
Need fix

2021-12-26 15:12 UTC, KirillKulakow commented on routes/api/contacts/index.js
> +router.patch('/:id', idValidate, updateValidate, updateContact)
насколько я помню здесь используется метод put

2021-12-26 15:13 UTC, KirillKulakow commented
файлы .DS_Store - не должны находится в гите, удалить и добавить в gitignore

2021-12-26 19:15 UTC, RitaDyvnych commented on controllers/contacts/index.js
> +  return res.status(HttpCode.OK).json({ status: 'success', code: HttpCode.OK, data: { ...contacts } })
исправила, это уже для пагинации/сортировок писалось

2021-12-26 19:15 UTC, RitaDyvnych commented on routes/api/contacts/index.js
> +router.patch('/:id', idValidate, updateValidate, updateContact)
невнимательность, исправила)

2021-12-27 19:08 UTC, KirillKulakow approved these changes

2021-12-28 07:40 UTC, merged