Hw04 auth
RitaDyvnych/nodejs-homework-REST-api pull request #3
Opened 2022-01-10 09:40 UTC by RitaDyvnych

2022-01-10 21:02 UTC, KirillKulakow commented on controllers/auth/index.js
> +  const response = await {
o_O что это за интерпретация?
для чего await?

2022-01-10 21:06 UTC, KirillKulakow requested changes
Need fix

2022-01-11 07:57 UTC, RitaDyvnych commented on controllers/auth/index.js
> +  const response = await {
видимо, на автомате уже писала везде, где есть async )
исправила

2022-01-11 19:57 UTC, KirillKulakow approved these changes

2022-01-12 11:17 UTC, merged