Hw06 email
RitaDyvnych/nodejs-homework-REST-api pull request #5
Opened 2022-01-24 15:10 UTC by RitaDyvnych

2022-01-24 18:58 UTC, KirillKulakow commented on model/user.js
> +      default: randomUUID(),
после запуска приложения у всех юзеров будет один и тот же токен

2022-01-24 18:58 UTC, KirillKulakow requested changes
Need fix

2022-01-24 20:04 UTC, RitaDyvnych commented on model/user.js
> +      default: randomUUID(),
исправила, теперь разный токен

2022-01-27 15:40 UTC, RitaDyvnych commented
все работает, проверьте, пожалуйста

2022-02-05 11:59 UTC, merged